server:
  port: 7777
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aisama_blog?serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
mybatis:
  mapper-locations: classpath:/mapper/*.xml