server:
  port: 443
  ssl:
    key-store: classpath:3166228_www.aisama.com.pfx
    key-store-password: xf2vBNRp
    key-store-type: PKCS12
#  servlet:
#    context-path: /blog/ 添加统一前缀
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aisama_blog?serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
  servlet:
    multipart:
      max-file-size: 10240000
mybatis:
  mapper-locations: classpath:/mapper/*.xml